# version: "3"
services:
  node-app:
   build: .
   ports:
     - '3000:3000'
   volumes:
     - ./:/app
     - /app/node_modules
   depends_on:
     - mongo-anyname
    
   environment:
   - ports:3000

  mongo-anyname:
   image: mongo
   environment:
     - MONGO_INITDB_ROOT_USERNAME=sidd
     - MONGO_INITDB_ROOT_PASSWORD=ishu@123

   volumes:
     - mongo-db:/data/db


volumes:
  mongo-db:
#   #  env_file:
#   #   - ./.env
  

# version: "3"
# services:
#   node-app:
#     build: .
#     ports:
#       - '3000:3000'
#     volumes:
#       - ./:/app
#       - /app/node_modules
#     environment:
#       - PORT=3000
#       - MONGO_URI=mongodb://sidd:ishu@123@mongo-anyname:27017
#     depends_on:
#       - mongo-anyname

#   mongo-anyname:
#     image: mongo
#     environment:
#        - MONGO_INITDB_ROOT_USERNAME=sidd
#        - MONGO_INITDB_ROOT_PASSWORD=ishu@123
